Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent

$relationships = Get-Content (Join-Path $repoRoot 'scripts/bootstrap/40-build-relationships.ps1') -Raw
$addToSolution = Get-Content (Join-Path $repoRoot 'scripts/bootstrap/50-add-to-solution.ps1') -Raw
$solutionIsolation = Get-Content (Join-Path $repoRoot 'scripts/bootstrap/helpers/solution-isolation.ps1') -Raw
$formsViews = Get-Content (Join-Path $repoRoot 'scripts/bootstrap/60-build-forms-views.ps1') -Raw
$demoScriptWizard = Get-Content (Join-Path $repoRoot 'scripts/bootstrap/06-demo-script-wizard.ps1') -Raw

foreach ($required in @('How long should the demo be, in minutes?', '$durationMinutes -lt 1', 'Duration minutes: $durationMinutes', 'Duration: $durationMinutes minutes')) {
  if ($demoScriptWizard -notmatch [regex]::Escape($required)) {
    throw "Demo script wizard duration intake appears incomplete: missing $required."
  }
}

if ($relationships -notmatch 'SchemaName\.Equals\(\$SchemaName') {
  throw 'Relationship existence check is missing an explicit returned-data SchemaName comparison.'
}

foreach ($required in @('ReferencedEntity', 'ReferencingEntity', 'Entity1LogicalName', 'Entity2LogicalName')) {
  if ($addToSolution -notmatch 'Get-PayloadEntityNames' -or $solutionIsolation -notmatch [regex]::Escape($required)) {
    throw "Payload-derived relationship entity lookup appears incomplete: missing $required."
  }
}

if ($formsViews -notmatch 'PrimaryIdAttribute') {
  throw 'Forms/views script does not query PrimaryIdAttribute.'
}

if ($formsViews -notmatch '\$resolvedPrimaryId') {
  throw 'Forms/views layout does not use resolved primary id field.'
}

foreach ($required in @('MinBusinessFieldsPerForm', 'MinBusinessColumnsPerView', 'IncludeOwnerOnForms', 'IncludeOwnerInViews', 'IncludeStatusInViews', 'PreferFormName', 'FailIfUnderpopulatedForms', 'FailIfUnderpopulatedViews', 'form-population-report.json', 'view-population-report.json', 'Get-ViewPopulationAnalysis', 'Generated by 60-build-forms-views.ps1')) {
  if ($formsViews -notmatch [regex]::Escape($required)) {
    throw "Forms/views hardening appears incomplete: missing $required."
  }
}

$bpfScript = Get-Content (Join-Path $repoRoot 'scripts/bootstrap/55-build-business-process-flows.ps1') -Raw
foreach ($required in @('EnableBusinessProcessFlow', 'BusinessProcessFlowName', 'PrimaryProcessEntity', 'FailIfBpfDefinitionIncomplete', 'PreferUpdateExistingBpf', 'business-process-flow-report.json', 'process-*.json')) {
  if ($bpfScript -notmatch [regex]::Escape($required)) {
    throw "BPF script appears incomplete: missing $required."
  }
}

$trackedScripts = @(& git -C $repoRoot ls-files --cached -- '*.ps1')
if ($LASTEXITCODE -ne 0) { throw 'Unable to enumerate tracked PowerShell scripts with Git.' }
$untrackedRepositoryScripts = @(& git -C $repoRoot ls-files --others --exclude-standard -- 'scripts/*.ps1' 'scripts/**/*.ps1')
if ($LASTEXITCODE -ne 0) { throw 'Unable to enumerate untracked repository PowerShell scripts with Git.' }
$repositoryScripts = @($trackedScripts + $untrackedRepositoryScripts | Sort-Object -Unique)
foreach ($relativeScriptPath in $repositoryScripts) {
  $scriptFile = Get-Item -LiteralPath (Join-Path $repoRoot $relativeScriptPath)
  $parseErrors = $null
  $parseTokens = $null
  [System.Management.Automation.Language.Parser]::ParseFile(
    $scriptFile.FullName,
    [ref]$parseTokens,
    [ref]$parseErrors
  ) | Out-Null
  if ($parseErrors.Count -gt 0) {
    throw "$relativeScriptPath has PowerShell parse errors: $(($parseErrors | ForEach-Object { $_.Message }) -join '; ')"
  }
}

Write-Host 'Script smoke checks passed.' -ForegroundColor Green
