<#
.SYNOPSIS
    Interactive sign-in helper. Authenticates to Azure and Power Platform,
    acquires a Dataverse bearer token, and saves environment values to a
    session env-vars file for use by the other bootstrap scripts.

.DESCRIPTION
    Prompts for all required values. Saves them to .env.ps1 in the repo root
    (git-ignored). All other bootstrap scripts dot-source .env.ps1 automatically
    so you only need to run this once per terminal session.

    Supports:
      - Interactive browser login (default)
      - Device code flow (headless / no browser)
      - Service principal login (CI/CD or tenant with MFA restrictions)

.EXAMPLE
    # Interactive (browser popup)
    pwsh ./scripts/bootstrap/10-auth-connect.ps1

    # Device code (no browser)
    pwsh ./scripts/bootstrap/10-auth-connect.ps1 -UseDeviceCode

    # Service principal
    pwsh ./scripts/bootstrap/10-auth-connect.ps1 -ServicePrincipal
#>

param(
    [switch]$UseDeviceCode,
    [switch]$ServicePrincipal
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "=== Auth Connect ===" -ForegroundColor Cyan
Write-Host "This script will sign you in and save your environment settings."
Write-Host "All values are stored locally only. Nothing is committed to source control."
Write-Host ""

# ── Collect environment details ────────────────────────────────────────────
$envUrl = Read-Host "Dataverse environment URL (e.g. https://your-org.crm.dynamics.com)"
$envUrl = $envUrl.TrimEnd("/")

$tenantId = Read-Host "Azure tenant ID or domain (leave blank to use default)"

Write-Host ""

# ── Azure sign-in ──────────────────────────────────────────────────────────
if ($ServicePrincipal) {
    Write-Host "Service principal login selected." -ForegroundColor Yellow
    $clientId     = Read-Host "Client (application) ID"
    $clientSecret = Read-Host "Client secret" -AsSecureString
    $plainSecret  = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
                        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($clientSecret))

    if ($tenantId) {
        az login --service-principal -u $clientId -p $plainSecret --tenant $tenantId | Out-Null
    } else {
        Write-Host "Tenant ID is required for service principal login." -ForegroundColor Red
        exit 1
    }
}
elseif ($UseDeviceCode) {
    Write-Host "Device code login: a code will be printed below." -ForegroundColor Yellow
    Write-Host "Visit https://microsoft.com/devicelogin and enter the code."
    if ($tenantId) {
        az login --use-device-code --tenant $tenantId | Out-Null
    } else {
        az login --use-device-code --allow-no-subscriptions | Out-Null
    }
}
else {
    Write-Host "Opening browser for interactive login..."
    if ($tenantId) {
        az login --tenant $tenantId | Out-Null
    } else {
        az login --allow-no-subscriptions | Out-Null
    }
}

Write-Host ""
Write-Host "Verifying Azure session..." -ForegroundColor Cyan
$account = az account show | ConvertFrom-Json
Write-Host "  Signed in as: $($account.user.name)"
Write-Host "  Tenant:       $($account.tenantId)"
Write-Host "  Subscription: $($account.name)"
Write-Host ""

# ── Get bearer token ───────────────────────────────────────────────────────
Write-Host "Acquiring Dataverse bearer token..."
$token = az account get-access-token --resource $envUrl --query accessToken -o tsv
if ([string]::IsNullOrWhiteSpace($token)) {
    Write-Host "Failed to acquire token. Verify the environment URL matches exactly." -ForegroundColor Red
    exit 1
}
Write-Host "Token acquired." -ForegroundColor Green

# ── Power Platform CLI auth profile ────────────────────────────────────────
Write-Host ""
Write-Host "Creating Power Platform CLI auth profile..."
pac auth create --url $envUrl | Out-Null
pac auth list

# ── Collect build config ───────────────────────────────────────────────────
Write-Host ""
Write-Host "=== Build Configuration ===" -ForegroundColor Cyan
$publisherName    = Read-Host "Publisher name (e.g. Contoso)"
$publisherPrefix  = Read-Host "Publisher prefix (3-8 lowercase chars, no spaces, e.g. cto)"
$solutionName     = Read-Host "Solution unique name (e.g. ContosoHRApp)"
$solutionDisplay  = Read-Host "Solution display name (e.g. Contoso HR Application)"

# ── Write session env file ─────────────────────────────────────────────────
$envFile = Join-Path (Split-Path $PSScriptRoot -Parent | Split-Path -Parent) ".env.ps1"

$content = @"
# Auto-generated by 10-auth-connect.ps1 — do not commit this file.
`$env:DV_ENVIRONMENT_URL    = "$envUrl"
`$env:DV_TOKEN              = "$token"
`$env:DV_PUBLISHER_NAME     = "$publisherName"
`$env:DV_PUBLISHER_PREFIX   = "$publisherPrefix"
`$env:DV_SOLUTION_NAME      = "$solutionName"
`$env:DV_SOLUTION_DISPLAY   = "$solutionDisplay"
`$global:DV_ENVIRONMENT_URL = "`$env:DV_ENVIRONMENT_URL"
`$global:DV_TOKEN           = "`$env:DV_TOKEN"
`$global:DV_PUBLISHER_NAME  = "`$env:DV_PUBLISHER_NAME"
`$global:DV_PUBLISHER_PREFIX= "`$env:DV_PUBLISHER_PREFIX"
`$global:DV_SOLUTION_NAME   = "`$env:DV_SOLUTION_NAME"
`$global:DV_SOLUTION_DISPLAY= "`$env:DV_SOLUTION_DISPLAY"
"@

Set-Content -Path $envFile -Value $content -Encoding UTF8
Write-Host ""
Write-Host "Session config saved to: $envFile" -ForegroundColor Green
Write-Host "All bootstrap scripts will load this automatically."
Write-Host ""
Write-Host "Next step: pwsh ./scripts/bootstrap/20-build-tables.ps1"

